services:
  app:
    container_name: api-papse
    build: .
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: mysql://root:supersecreto@db:3306/papse_db
      JWT_SECRET: supersecreto
    dns:
      - 8.8.8.8
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # command: tail -f /dev/null

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: supersecreto
      MYSQL_DATABASE: papse_db
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: supersecreto
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: